fixrtm/fixRTM

- .idea/compiler.xml
- build.gradle
> fix: debugClassLoadingSaveがデフォルトでonである問題

- build.gradle
- patches/ngtlib.patch
> Permit command cant exclude from server console

- build.gradle
> fix: runClientでログインしない問題

- patches/rtm.patch
> fix: 車輌自体の当たり判定が描画されない問題

- patches/rtm.patch
> fix: マルチにてEntityBogieがclientで生成されない事がある問題

- build.gradle
- makePatch.gradle
- src/main/java/com/anatawa12/fixRtm/FixRtm.kt
- src/main/resources/META-INF/fix-rtm_at.cfg
> Use accesstransformer

- patches/rtm.patch
- src/main/java/com/anatawa12/fixRtm/rtm/Hooks.kt
> Dismout position is invalid

- src/main/java/com/anatawa12/fixRtm/rtm/Hooks.kt
> fix: マーカー見るとクラッシュする

- .editorconfig
- build.gradle
- patches/rtm.patch
- src/main/java/com/anatawa12/fixRtm/asm/FixRtmCorePlugin.kt
- src/main/java/com/anatawa12/fixRtm/asm/Preprocessor.kt
- src/main/java/com/anatawa12/fixRtm/asm/PreprocessorTransformer.kt
- src/main/java/com/anatawa12/fixRtm/asm/config/KVSConfig.kt
- src/main/java/com/anatawa12/fixRtm/asm/config/MainConfig.kt
> Marker distance is not real

- patches/ngtlib.patch
- src/main/java/com/anatawa12/fixRtm/FixRtm.kt
- src/main/java/com/anatawa12/fixRtm/Utils.kt
- src/main/java/com/anatawa12/fixRtm/asm/config/MainConfig.kt
- src/main/java/com/anatawa12/fixRtm/ngtlib/renderer/model/CachedPolygonModel.kt
- src/main/java/com/anatawa12/fixRtm/ngtlib/renderer/model/CachedPolygonModelFormat.txt
- src/main/java/com/anatawa12/fixRtm/ngtlib/renderer/model/ModelLoader.kt
- src/main/java/com/anatawa12/fixRtm/rtm/modelpack/init/ExModelPackConstructThread.kt
- src/main/java/com/anatawa12/fixRtm/utils/ArrayPool.kt
- src/main/java/com/anatawa12/fixRtm/utils/MultiCloseScope.kt
> Cache of models

- src/main/java/com/anatawa12/fixRtm/caching/ModelPackBasedCache.kt
- src/main/java/com/anatawa12/fixRtm/caching/TaggedFileManager.kt
- src/main/java/com/anatawa12/fixRtm/io/FIXFileLoader.kt
- src/main/java/com/anatawa12/fixRtm/ngtlib/renderer/model/CachedPolygonModel.kt
- src/main/java/com/anatawa12/fixRtm/ngtlib/renderer/model/ModelLoader.kt
- src/main/java/com/anatawa12/fixRtm/utils/DigestUtils.kt
- src/main/java/com/anatawa12/fixRtm/utils/FileCache.kt
> Change cache format

- src/main/java/com/anatawa12/fixRtm/Utils.kt
- src/main/java/com/anatawa12/fixRtm/caching/FileCache.kt
キャッシュを圧縮し、また不要なディレクトリを生成しないようにする
> Better cache

- build.gradle
- src/main/resources/LICENSE.txt
- src/main/resources/README.txt
- src/main/resources/kotlin-LICENSE.txt
- src/main/resources/rhino-LICENSE.txt
> fix Build faired with ZipException and add License and Readme in jar

- src/main/java/com/anatawa12/fixRtm/scripting/FIXScriptUtil.kt
- src/main/java/com/anatawa12/fixRtm/scripting/ScriptCompiledClassCache.kt
> 'jp' is loaded as SPacketPlayerListItem

- src/main/java/com/anatawa12/fixRtm/Utils.kt
- src/main/java/com/anatawa12/fixRtm/caching/FileCache.kt
- src/main/java/com/anatawa12/fixRtm/caching/TaggedFileManager.kt
> Revert b1576ea4 and some fixes

- src/main/java/com/anatawa12/fixRtm/caching/FileCache.kt
- src/main/java/com/anatawa12/fixRtm/caching/ModelPackBasedCache.kt
- src/main/java/com/anatawa12/fixRtm/scripting/ExecutedScript.kt
- src/main/java/com/anatawa12/fixRtm/scripting/FIXScriptUtil.kt
> IOException never catched in readScopeData

- patches/rtm.patch
> execScriptFuncのエラーがすべてinit script扱いされている

- src/main/java/com/anatawa12/fixRtm/scripting/FIXScriptUtil.kt
- src/main/java/com/anatawa12/fixRtm/scripting/ScriptImporter.kt
> Add modelpack name to name of the source code

- src/main/java/com/anatawa12/fixRtm/asm/RhinoTransformer.kt
- src/main/java/com/anatawa12/fixRtm/scripting/PrimitiveJavaHelper.kt
- src/main/java/com/anatawa12/fixRtm/scripting/inRhinoPackage.kt
> crash when click search light

- src/main/java/com/anatawa12/fixRtm/scripting/ScriptCompiledClassCache.kt
> NPT at NativeRegExp.getFlags

- src/main/java/com/anatawa12/fixRtm/io/FIXFileLoader.kt
> fix: RTM with fixRTM in 1.12.2 dir will be crashed

- src/main/java/com/anatawa12/fixRtm/asm/RhinoTransformer.kt
- src/main/java/com/anatawa12/fixRtm/scripting/CodeGenHooks.kt
- src/main/java/com/anatawa12/fixRtm/scripting/FIXScriptEngine.kt
> Crash models by hojo

- patches/ngtlib.patch
> /permit listをサーバーコンソールから実行できるようにする

- patches/ngtlib.patch
- src/main/java/com/anatawa12/fixRtm/asm/config/MainConfig.kt
> Negative permissions

- src/main/java/com/anatawa12/fixRtm/io/FIXFileLoader.kt
> ZIPのエラーメッセージが正しくない

- src/main/java/com/anatawa12/fixRtm/scripting/rhino/FIXRhinoScriptEngine.kt
> fix: instanceof for parameters from ScriptEngine always false

- build.gradle
> fix: first build fail

- patches/rtm.patch
- src/main/java/com/anatawa12/fixRtm/FixRtm.kt
- src/main/java/com/anatawa12/fixRtm/rtm/modelpack/modelset/dummies/DummyModelSets.kt
- src/main/resources/assets/fix-rtm/scripts/render-gear.js
> Support ModelSetMechanism

- .github/workflows/release.yml
- scripts/update_for_release.sh
> use makeFixrtmJar to build and get libs in fixrtm dir

- patches/rtm.patch
- processMods.gradle
> RTM 2.4.21

- patches/rtm.patch
> getPickBlock should returns ItemStack.EMPTY instead null.

- patches/rtm.patch
> fix: NPE in EntityVehicleBase.fixRiderPosOnDismount

- src/main/java/com/anatawa12/fixRtm/FixRtm.kt
- src/main/java/com/anatawa12/fixRtm/Utils.kt
> Warn if fixRTM is added only on server

- patches/rtm.patch
- src/main/java/com/anatawa12/fixRtm/Utils.kt
> fix crash due to accessing client-only method, func_174822_a

- src/main/java/com/anatawa12/fixRtm/Hooks.kt
> fix: Speed never updated

- .patching-mods/rtm.patching-mod/modified-classes.txt
- src/main/rtm-patches/jp/ngt/rtm/entity/train/util/Formation.java.pm.patch
> NPE in is front car

- src/main/java/com/anatawa12/fixRtm/Utils.kt
- src/main/ngtlib-patches/jp/ngt/ngtlib/item/craft/RecipeManager.java.pm.patch
- src/main/ngtlib-patches/jp/ngt/ngtlib/item/craft/ShapedRecipes55.java.pm.patch
> fix: RecipeManager.getRecipeItems returns array with null items.

- build.gradle.kts
- src/main/java/com/anatawa12/fixRtm/FixRtm.kt
- src/main/java/com/anatawa12/fixRtm/asm/FixRtmCorePlugin.kt
- src/main/java/com/anatawa12/fixRtm/asm/patching/PatchingFixRtmCorePlugin.kt
> relocate kotlin and other libraries

- src/main/java/com/anatawa12/fixRtm/Utils.kt
> support returning null from NetworkDispatcher.get

- .patching-mods/ngtlib.patching-mod/modified-classes.txt
- src/main/ngtlib-patches/jp/ngt/ngtlib/util/NGTUtil.java.pm.patch
> opened lan server not work

- src/main/ngtlib-patches/jp/ngt/ngtlib/util/PermissionManager.java.pm.patch
> restore fixrtm.all_permit

- .patching-mods/ngtlib.patching-mod/modified-classes.txt
- src/main/ngtlib-patches/jp/ngt/ngtlib/io/ScriptUtil.java.pm.patch
Fixes #195, Improves #164 
This will be merged after release because this may make breaking changes to existing model packs
> java.lang.VerifyError: Incompatible argument to function

- src/main/rtm-patches/jp/ngt/rtm/entity/train/util/Formation.java.pm.patch
> crash when connected two train

- src/main/java/com/anatawa12/fixRtm/FixHooks.kt
- src/main/java/com/anatawa12/fixRtm/asm/hooking/HookingTransformer.kt
- src/main/rtm-patches/jp/ngt/rtm/modelpack/ModelPackManager.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/modelpack/init/ModelPackLoadThread.java.pm.patch
> add confirm for loading world if model loading is not finished

- .patching-mods/rtm.patching-mod/modified-classes.txt
- src/main/rtm-patches/jp/ngt/rtm/event/RTMKeyHandlerClient.java.pm.patch
> Mouse may not work as a key

- README.en.md
- README.md
See Kai-Z-JP/KaizPatchX#34, Kai-Z-JP/KaizPatchX#35
> add link to KaizPatchX

- .patching-mods/rtm.patching-mod/modified-classes.txt
- src/main/rtm-patches/jp/ngt/rtm/item/ItemRail.java.pm.patch
> fix: NPE when pick before sync rail data

- .github/ISSUE_TEMPLATE/bug-report-en.md
- .github/ISSUE_TEMPLATE/bug-report-ja.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request-en.md
- .github/ISSUE_TEMPLATE/feature-request-ja.md
> Issue template

- src/main/rtm-patches/jp/ngt/rtm/entity/train/EntityTrainBase.java.pm.patch
> fix Accelerates when braking after go backward

- .patching-mods/rtm.patching-mod/modified-classes.txt
- src/main/rtm-patches/jp/ngt/rtm/CreativeTabRTM.java.pm.patch
> add workaround for rebof

- .patching-mods/ngtlib.patching-mod/modified-classes.txt
- src/main/ngtlib-patches/jp/ngt/ngtlib/network/PacketNBT.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/entity/vehicle/VehicleTrackerEntry.java.pm.patch
> Some model can be default model at the login

- src/main/rtm-patches/jp/ngt/rtm/item/ItemRail.java.pm.patch
> fix/improve compatibility with Hwyla

- src/main/rtm-patches/jp/ngt/rtm/modelpack/ModelPackManager.java.pm.patch
> move `Send model to client` log to trace, debug.log

- .patching-mods/ngtlib.patching-mod/modified-classes.txt
- .patching-mods/rtm.patching-mod/modified-classes.txt
- build.gradle.kts
- src/main/java/com/anatawa12/fixRtm/FixRtm.kt
- src/main/java/com/anatawa12/fixRtm/KeyboardUtil.kt
- src/main/java/com/anatawa12/fixRtm/Utils.kt
- src/main/java/com/anatawa12/fixRtm/gui/GuiChangeOffset.kt
- src/main/java/com/anatawa12/fixRtm/gui/GuiHandler.kt
- src/main/java/com/anatawa12/fixRtm/gui/GuiId.kt
- src/main/ngtlib-patches/jp/ngt/ngtlib/block/TileEntityPlaceable.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/block/BlockMachineBase.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/RenderMachine.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/TileEntityCrossingGate.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/TileEntityMachineBase.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/TileEntityPoint.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/TileEntityTrainWorkBench.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/entity/train/EntityTrainBase.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/entity/train/util/Formation.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/entity/vehicle/RenderVehicleBase.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/RenderMarkerBlock.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/RenderTurntable.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/TileEntityMarker.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/TileEntityTurnTableCore.java.pm.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/util/MarkerState.java.pm.patch
Closes #246
ports Kai-Z-JP/KaizPatchX#47
ports Kai-Z-JP/KaizPatchX@8a1a50c
ports Kai-Z-JP/KaizPatchX@d121fa7
ports Kai-Z-JP/KaizPatchX@b44704b
ports Kai-Z-JP/KaizPatchX@c79412a
ports Kai-Z-JP/KaizPatchX@d1f12b1
ports Kai-Z-JP/KaizPatchX@822adad
ports Kai-Z-JP/KaizPatchX@7781bca
ports Kai-Z-JP/KaizPatchX@0823ab2
ports a little Kai-Z-JP/KaizPatchX@eae3559
> port Kaiz patch 1.2

- .patching-mods/rtm.patching-mod/modified-classes.txt
- src/main/rtm-patches/jp/ngt/rtm/network/PacketModelPack.java.pm.patch
> fix: we may not be possible to call ByteBuf#array()

- src/main/rtm-patches/jp/ngt/rtm/entity/vehicle/EntityVehicleBase.java.pm.patch
> remove printStackTrace from fixRiderPosOnDismount

- src/main/java/com/anatawa12/fixRtm/rtm/entity/train/EntityBogie.kt
- src/main/java/com/anatawa12/fixRtm/rtm/entity/vehicle/EntityVehicleBase.kt
> fix java.lang.RuntimeException: Missing 

- .patching-mods/main.yaml
- src/main/rtm-patches/jp/ngt/rtm/RTMSound.java.patch
> fix: sound by rtm can not be found

- src/main/java/com/anatawa12/fixRtm/ngtlib/renderer/model/PolygonModelCharsetDetector.kt
- src/main/ngtlib-patches/jp/ngt/ngtlib/renderer/model/PolygonModel.java.patch
> fix: all model files will be read as platform-native charset

- src/main/rtm-patches/jp/ngt/rtm/rail/BlockMarker.java.patch
> fix NPE in BlockMarker

- .patching-mods/main.yaml
- src/main/java/com/anatawa12/fixRtm/Utils.kt
- src/main/ngtlib-patches/jp/ngt/ngtlib/io/NGTFileLoader.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/BlockRailroadSign.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/RenderRailroadSign.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/TileEntityRailroadSign.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockSignal.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/RenderSignal.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/TileEntitySignal.java.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/BlockLargeRailBase.java.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/TileEntityLargeRailBase.java.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/TileEntityLargeRailCore.java.patch
skipped:
- Kai-Z-JP/KaizPatchX#80, Kai-Z-JP/KaizPatchX@e7a7f6c61048e36bb6ae32f80aae7b25cadb3cab
> I'm worried about turntable support.
- Kai-Z-JP/KaizPatchX#97, Kai-Z-JP/KaizPatchX@958ac0027ad8f09ddbe0a04ffef65371e94d412e
> I can't found same code in 1.12.2
- Kai-Z-JP/KaizPatchX#125, Kai-Z-JP/KaizPatchX@c6bc12f34bde4c7d0a9cd12437ea46a5cd6a3e97
> I can't read what the update fixes or improves.
> Port kaizpatchx 1.3

- src/main/rtm-patches/jp/ngt/rtm/event/RTMKeyHandlerClient.java.patch
> NPE when playing hone but not configured in json

- src/main/java/com/anatawa12/fixRtm/rtm/modelpack/init/ExModelPackConstructThread.kt
- src/main/java/com/anatawa12/fixRtm/rtm/modelpack/init/UnconstructSetsQueue.kt
- src/main/rtm-patches/jp/ngt/rtm/modelpack/ModelPackManager.java.patch
- src/main/rtm-patches/jp/ngt/rtm/modelpack/init/ModelPackConstructThread.java.patch
> thread safe unconstructSets

- src/main/rtm-patches/jp/ngt/rtm/command/CommandRTM.java.patch
> allow run delAllTrain from server console

- src/main/rtm-patches/jp/ngt/rtm/entity/train/EntityBogie.java.patch
> driveTrain is not allowed even if op or permitted

- src/main/java/com/anatawa12/fixRtm/FixRtm.kt
- src/main/java/com/anatawa12/fixRtm/asm/config/MainConfig.kt
> fix Sounds from Immersive vehicles not working

- .patching-mods/main.yaml
- src/main/rtm-patches/jp/ngt/rtm/entity/train/EntityTrainBase.java.patch
- src/main/rtm-patches/jp/ngt/rtm/entity/train/util/EnumNotch.java.patch
- src/main/rtm-patches/jp/ngt/rtm/modelpack/cfg/TrainConfig.java.patch
> Variable ac/deceleration

- src/main/rtm-patches/jp/ngt/rtm/entity/train/EntityBogie.java.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/BlockLargeRailBase.java.patch
Closes #319 
Ports: Kai-Z-JP/KaizPatchX#170
レールに伝える信号の判定を車両中央基準から台車基準に変更
> Fix The train is on the rails is detected by the another rail nearby too

- src/main/ngtlib-patches/jp/ngt/ngtlib/io/NGTFileLoader.java.patch
> Always use FIXFileLoader for modelpack loading

- build.gradle.kts
- src/main/java/com/anatawa12/fixRtm/FixRtm.kt
> Add support for webp images

- src/main/java/com/anatawa12/fixRtm/PermissionManager.kt
- src/main/ngtlib-patches/jp/ngt/ngtlib/util/PermissionManager.java.patch
> Do not add `fixrtm.all_permit` if not enabled

- src/main/rtm-patches/jp/ngt/rtm/rail/BlockMarker.java.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/TileEntityMarker.java.patch
> Marker search algorithm

- src/main/java/com/anatawa12/fixRtm/asm/config/MainConfig.kt
> make addModelPackInformationInAllCrashReports false by default

- src/main/rtm-patches/jp/ngt/rtm/rail/BlockMarker.java.patch
> fix marker not working

- src/main/rtm-patches/jp/ngt/rtm/event/RTMKeyHandlerClient.java.patch
> fix Crash if sneak or jump key is a mouse button.

- .github/license-check/header-check.json
- build.gradle.kts
> exclude distResources/META-INF/services from license header check

- .github/workflows/release.yml
> fix release note for stable releases

- .patching-mods/main.yaml
- src/main/rtm-patches/jp/ngt/rtm/gui/GuiSelectModel.java.patch
- src/main/rtm-patches/jp/ngt/rtm/item/ItemWithModel.java.patch
- src/main/rtm-patches/jp/ngt/rtm/modelpack/IResourceSelector.java.patch
> Fix some model may be detected as another kind on inventory

- .patching-mods/main.yaml
- src/main/java/com/anatawa12/fixRtm/ngtlib/renderer/model/PolygonModelCharsetDetector.kt
- src/main/ngtlib-patches/jp/ngt/ngtlib/io/NGTText.java.patch
> Add charset detection for scripts

- .patching-mods/main.yaml
- src/main/ngtlib-patches/jp/ngt/ngtlib/renderer/media/GIF.java.patch
> fix Rendering ThinEBB make game crashed

- .github/workflows/build.yml
- .github/workflows/release.yml
> use eskatos/gradle-command-action@v2

- src/main/ngtlib-patches/.gitattributes
- src/main/rtm-patches/.gitattributes
Because dependabot doesn't run gradle script, generated files are not updated.
> update generated .gitattributes

- .idea/jarRepositories.xml
- src/main/rtm-patches/jp/ngt/rtm/rail/BlockMarker.java.patch
> use as same sorting for marker search as possible

- .github/license-check/header-check.json
- src/main/kotlin/jp/ngt/rtm/command/CommandRTM.kt
- src/main/resources/assets/fix-rtm/lang/en_US.lang
- src/main/rtm-patches/jp/ngt/rtm/command/CommandRTM.java.patch
- src/main/rtm-patches/jp/ngt/rtm/item/ItemTrain.java.patch
Closes #395
Ports: Kai-Z-JP/KaizPatchX#205
Ports: Kai-Z-JP/KaizPatchX@25e4018f269da5f4eb75e44576191d570e3b24e7
> Port /rtm (door|pan|speed|summon)

- .patching-mods/main.yaml
- src/main/java/com/anatawa12/fixRtm/Utils.kt
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockElectricalWiring.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/RenderElectricalWiring.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/TileEntityConnectorBase.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/TileEntityElectricalWiring.java.patch
Ports: https://github.com/Kai-Z-JP/KaizPatchX/pull/180
Co-authored-by: Kaiz <kaiz@kaiz.jp>
> implement offset for Insulators

- .patching-mods/main.yaml
- src/main/java/com/anatawa12/fixRtm/rtm/block/BlockOrnamentBase.kt
- src/main/rtm-patches/jp/ngt/rtm/block/BlockFluorescent.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/BlockLinePole.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/BlockPipe.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/BlockPlant.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/BlockScaffold.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/BlockScaffoldStairs.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/TileEntityOrnament.java.patch
- src/main/rtm-patches/jp/ngt/rtm/item/ItemInstalledObject.java.patch
This implementation uses crowbar for configure offset of Ornament
Ports: https://github.com/Kai-Z-JP/KaizPatchX/commit/0af19c48a76157f1ced1dd830b4e7c316788b8cd
> implement offset for Ornament

- src/main/java/com/anatawa12/fixRtm/rtm/Hooks.kt
- src/main/rtm-patches/jp/ngt/rtm/rail/BlockMarker.java.patch
- src/main/rtm-patches/jp/ngt/rtm/rail/util/RailMaker.java.patch
> reimplement 7c29afa95ea1863eee1d41d60c1402057fc42f83

- src/main/rtm-patches/jp/ngt/rtm/entity/train/EntityTrainBase.java.patch
Closes #397
Ports: Kai-Z-JP/KaizPatchX#214
> Brake release sound doesn't sound when setNotch

- .patching-mods/main.yaml
- src/main/rtm-patches/jp/ngt/rtm/entity/train/EntityTrainBase.java.patch
- src/main/rtm-patches/jp/ngt/rtm/entity/train/util/TrainState.java.patch
- src/main/rtm-patches/jp/ngt/rtm/entity/vehicle/EntityVehicleBase.java.patch
> Fix crash /mctrl dir if invalid value is passed

- src/main/rtm-patches/jp/ngt/rtm/gui/GuiVehicleControlPanel.java.patch
Closes #403 
Ports: Kai-Z-JP/KaizPatchX@6470db9032fccf747f56ce94cba975ff50885d71
> Fix crash if train model is changed and button is out of range

- src/main/rtm-patches/jp/ngt/rtm/gui/GuiVehicleControlPanel.java.patch
Closes #404 
Ports: Kai-Z-JP/KaizPatchX@9c635a7b2f225748e8dc08ab3f7470c93470d5ba
> Port F key to sync custom button status to all trains in the formation

- src/main/rtm-patches/jp/ngt/rtm/item/ItemWithModel.java.patch
Closes #400 
Ports: Kai-Z-JP/KaizPatchX@756f38c140af59250acb3c69520680efe4d6de89
> Display whether the item has DataMap or not on item tooltip

- src/main/rtm-patches/jp/ngt/rtm/item/ItemWithModel.java.patch
> Fix NPE on many times at addMoreInfo

- src/main/java/com/anatawa12/fixRtm/rtm/block/BlockOrnamentBase.kt
- src/main/java/com/anatawa12/fixRtm/rtm/item/ItemWithModelEx.kt
- src/main/rtm-patches/jp/ngt/rtm/block/BlockMachineBase.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockElectricalWiring.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockSignal.java.patch
- src/main/rtm-patches/jp/ngt/rtm/item/ItemInstalledObject.java.patch
- src/main/rtm-patches/jp/ngt/rtm/item/ItemWithModel.java.patch
> implement pick offsets

- src/main/java/com/anatawa12/fixRtm/network/NetworkHandler.kt
- src/main/java/com/anatawa12/fixRtm/network/RequestFormation.kt
- src/main/rtm-patches/jp/ngt/rtm/entity/train/EntityTrainBase.java.patch
> Fix リログ時にFormation情報がクライアントに共有されてない

- .patching-mods/main.yaml
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockConnector.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockElectricalWiring.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockInsulator.java.patch
> fix: picking connectors will pick insulator

- src/main/rtm-patches/jp/ngt/rtm/block/BlockRailroadSign.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockElectricalWiring.java.patch
- src/main/rtm-patches/jp/ngt/rtm/electric/BlockSignal.java.patch
> fix: Some block still use block item to change offsets

- .patching-mods/main.yaml
- src/main/rtm-patches/jp/ngt/rtm/block/BlockSignBoard.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/RenderSignBoard.java.patch
- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/TileEntitySignBoard.java.patch
- src/main/rtm-patches/jp/ngt/rtm/item/ItemInstalledObject.java.patch
> implement offsets for signboard

- src/main/ngtlib-patches/jp/ngt/ngtlib/block/TileEntityPlaceable.java.patch
> save & sync offsets

- src/main/rtm-patches/jp/ngt/rtm/rail/BlockMarker.java.patch
> fix NPE on client thread from marker

- src/main/rtm-patches/jp/ngt/rtm/rail/BlockMarker.java.patch
> fix: no switch type error

- src/main/java/com/anatawa12/fixRtm/rtm/item/ItemWithModelEx.kt
https://discord.com/channels/749186892733480970/749187819812945960/980082146641313823
> fix(offsets):on place blocks, rotation is not correct

- src/main/rtm-patches/jp/ngt/rtm/block/tileentity/TileEntityFluorescent.java.patch
> fix(offsets/fluorescent): fluorescent may be placed to opposite

- src/main/kotlin/jp/ngt/rtm/command/CommandRTM.kt
> fix(commands/rtm/delAllTrain): delAllTrain doesn't remove any entities

- src/main/rtm-patches/jp/ngt/rtm/electric/TileEntityConnectorBase.java.patch
Fixes #487, #486 
This is a hotfix. Should be released soon.
> fix(rendering/wire): NPE on load

- .github/workflows/comment-link-to-nightly-link.yml
- .github/workflows/conventionalcommits.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- README.en.md
- README.md
> New commit rule improvements

- .github/workflows/check-license.yml
> ci: run check-license on pull_request trigger

- .github/license-check/header-check.json
- .gitignore
- CONTRIBUTING.md
- githooks/commit-msg
- githooks/install.sh
- githooks/pre-commit
Add git hooks for local checks
> Pre commit hook
